Individually Delete Records
beda-software/drf-writable-nested pull request #103
Opened 2020-02-23 15:06 UTC by ehutch79

Given the Meta field 'individual_delete' iterate over records to delete and call the delete method indvidually.

Otherwise retail the default behavior and bulk delete items.

Fixes beda-software/drf-writable-nested#102

2020-05-11 21:26 UTC, cjnething commented
This is super helpful - can it get merged in? Thanks!

2021-01-20 16:02 UTC, ehutch79 commented
Hi!

It's been nearly a year. Is there any comment on this? Why it hasn't been merged or rejected?

2021-04-01 16:42 UTC, auvipy requested changes
can you also add test for the proposed change?

2021-05-26 17:51 UTC, ruscoder commented
I like the general solution @kavdev suggested using perform_nested_delete. So, closing for now.

2021-05-26 17:51 UTC, closed without merging